---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.6
    container_name: jellyfin
    environment:
      - PUID=1000 # À vérifier avec la commande 'id' dans votre terminal
      - PGID=1000 # À vérifier avec la commande 'id' dans votre terminal
      - TZ=Europe/Paris
    volumes:
      - /jellyfin-config:/config:rw
      - /mnt/Partage:/data:rw # Chemin vers vos films/séries
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # Donne accès au moteur de rendu graphique
    restart: unless-stopped

  seerr:
    image: seerr/seerr:latest
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - "/mnt/Partage/Logiciels/seerr/config:/app/config:rw"
    ports:
      - 5055:5055
    restart: unless-stopped
    depends_on:
      - jellyfin
